package org.literacyapp.dao;

import org.literacyapp.model.enums.Locale;
import org.literacyapp.model.enums.content.allophone.ConsonantPlace;
import org.literacyapp.model.enums.content.allophone.ConsonantType;
import org.literacyapp.model.enums.content.allophone.ConsonantVoicing;
import org.literacyapp.model.enums.content.allophone.LipRounding;
import org.literacyapp.model.enums.content.allophone.SoundType;
import org.literacyapp.model.enums.content.allophone.VowelFrontness;
import org.literacyapp.model.enums.content.allophone.VowelHeight;
import org.literacyapp.model.enums.content.allophone.VowelLength;

import java.util.Calendar;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ALLOPHONE".
 */
public class Allophone {

    private Long id;
    private Locale locale;
    private Calendar timeLastUpdate;
    private Integer revisionNumber;
    private String valueIpa;
    private String valueSampa;
    private SoundType soundType;
    private VowelLength vowelLength;
    private VowelHeight vowelHeight;
    private VowelFrontness vowelFrontness;
    private LipRounding lipRounding;
    private ConsonantType consonantType;
    private ConsonantPlace consonantPlace;
    private ConsonantVoicing consonantVoicing;

    public Allophone() {
    }

    public Allophone(Long id) {
        this.id = id;
    }

    public Allophone(Long id, Locale locale, Calendar timeLastUpdate, Integer revisionNumber, String valueIpa, String valueSampa, SoundType soundType, VowelLength vowelLength, VowelHeight vowelHeight, VowelFrontness vowelFrontness, LipRounding lipRounding, ConsonantType consonantType, ConsonantPlace consonantPlace, ConsonantVoicing consonantVoicing) {
        this.id = id;
        this.locale = locale;
        this.timeLastUpdate = timeLastUpdate;
        this.revisionNumber = revisionNumber;
        this.valueIpa = valueIpa;
        this.valueSampa = valueSampa;
        this.soundType = soundType;
        this.vowelLength = vowelLength;
        this.vowelHeight = vowelHeight;
        this.vowelFrontness = vowelFrontness;
        this.lipRounding = lipRounding;
        this.consonantType = consonantType;
        this.consonantPlace = consonantPlace;
        this.consonantVoicing = consonantVoicing;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Locale getLocale() {
        return locale;
    }

    public void setLocale(Locale locale) {
        this.locale = locale;
    }

    public Calendar getTimeLastUpdate() {
        return timeLastUpdate;
    }

    public void setTimeLastUpdate(Calendar timeLastUpdate) {
        this.timeLastUpdate = timeLastUpdate;
    }

    public Integer getRevisionNumber() {
        return revisionNumber;
    }

    public void setRevisionNumber(Integer revisionNumber) {
        this.revisionNumber = revisionNumber;
    }

    public String getValueIpa() {
        return valueIpa;
    }

    public void setValueIpa(String valueIpa) {
        this.valueIpa = valueIpa;
    }

    public String getValueSampa() {
        return valueSampa;
    }

    public void setValueSampa(String valueSampa) {
        this.valueSampa = valueSampa;
    }

    public SoundType getSoundType() {
        return soundType;
    }

    public void setSoundType(SoundType soundType) {
        this.soundType = soundType;
    }

    public VowelLength getVowelLength() {
        return vowelLength;
    }

    public void setVowelLength(VowelLength vowelLength) {
        this.vowelLength = vowelLength;
    }

    public VowelHeight getVowelHeight() {
        return vowelHeight;
    }

    public void setVowelHeight(VowelHeight vowelHeight) {
        this.vowelHeight = vowelHeight;
    }

    public VowelFrontness getVowelFrontness() {
        return vowelFrontness;
    }

    public void setVowelFrontness(VowelFrontness vowelFrontness) {
        this.vowelFrontness = vowelFrontness;
    }

    public LipRounding getLipRounding() {
        return lipRounding;
    }

    public void setLipRounding(LipRounding lipRounding) {
        this.lipRounding = lipRounding;
    }

    public ConsonantType getConsonantType() {
        return consonantType;
    }

    public void setConsonantType(ConsonantType consonantType) {
        this.consonantType = consonantType;
    }

    public ConsonantPlace getConsonantPlace() {
        return consonantPlace;
    }

    public void setConsonantPlace(ConsonantPlace consonantPlace) {
        this.consonantPlace = consonantPlace;
    }

    public ConsonantVoicing getConsonantVoicing() {
        return consonantVoicing;
    }

    public void setConsonantVoicing(ConsonantVoicing consonantVoicing) {
        this.consonantVoicing = consonantVoicing;
    }

}
