package org.literacyapp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "AUDIO".
 */
public class Audio {

    private Long id;
    private Long serverId;
    private String language;
    private String title;

    public Audio() {
    }

    public Audio(Long id) {
        this.id = id;
    }

    public Audio(Long id, Long serverId, String language, String title) {
        this.id = id;
        this.serverId = serverId;
        this.language = language;
        this.title = title;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getServerId() {
        return serverId;
    }

    public void setServerId(Long serverId) {
        this.serverId = serverId;
    }

    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

}
