package org.literacyapp.dao;

import org.literacyapp.model.enums.Locale;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "AUDIO".
 */
public class Audio {

    private Long id;
    private Locale locale;
    private String title;

    public Audio() {
    }

    public Audio(Long id) {
        this.id = id;
    }

    public Audio(Long id, Locale locale, String title) {
        this.id = id;
        this.locale = locale;
        this.title = title;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Locale getLocale() {
        return locale;
    }

    public void setLocale(Locale locale) {
        this.locale = locale;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

}
