package org.literacyapp.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import org.literacyapp.dao.AllophoneDao;
import org.literacyapp.dao.LetterDao;
import org.literacyapp.dao.AudioDao;
import org.literacyapp.dao.WordDao;
import org.literacyapp.dao.NumberDao;
import org.literacyapp.dao.ImageDao;
import org.literacyapp.dao.VideoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1001014): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1001014;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        AllophoneDao.createTable(db, ifNotExists);
        LetterDao.createTable(db, ifNotExists);
        AudioDao.createTable(db, ifNotExists);
        WordDao.createTable(db, ifNotExists);
        NumberDao.createTable(db, ifNotExists);
        ImageDao.createTable(db, ifNotExists);
        VideoDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        AllophoneDao.dropTable(db, ifExists);
        LetterDao.dropTable(db, ifExists);
        AudioDao.dropTable(db, ifExists);
        WordDao.dropTable(db, ifExists);
        NumberDao.dropTable(db, ifExists);
        ImageDao.dropTable(db, ifExists);
        VideoDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(AllophoneDao.class);
        registerDaoClass(LetterDao.class);
        registerDaoClass(AudioDao.class);
        registerDaoClass(WordDao.class);
        registerDaoClass(NumberDao.class);
        registerDaoClass(ImageDao.class);
        registerDaoClass(VideoDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
