package org.literacyapp.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import org.literacyapp.model.content.Allophone;
import org.literacyapp.model.content.Letter;
import org.literacyapp.model.content.multimedia.Audio;
import org.literacyapp.model.content.multimedia.Image;
import org.literacyapp.model.content.multimedia.JoinAudiosWithLetters;
import org.literacyapp.model.content.multimedia.JoinAudiosWithNumbers;
import org.literacyapp.model.content.multimedia.JoinAudiosWithWords;
import org.literacyapp.model.content.multimedia.JoinImagesWithLetters;
import org.literacyapp.model.content.multimedia.JoinImagesWithNumbers;
import org.literacyapp.model.content.multimedia.JoinImagesWithWords;
import org.literacyapp.model.content.multimedia.JoinVideosWithLetters;
import org.literacyapp.model.content.multimedia.JoinVideosWithNumbers;
import org.literacyapp.model.content.multimedia.JoinVideosWithWords;
import org.literacyapp.model.content.multimedia.Video;
import org.literacyapp.model.content.Number;
import org.literacyapp.model.content.Word;
import org.literacyapp.model.Device;
import org.literacyapp.model.JoinStudentsWithDevices;
import org.literacyapp.model.Student;
import org.literacyapp.model.StudentImage;
import org.literacyapp.model.StudentImageFeature;
import org.literacyapp.model.analytics.AuthenticationEvent;
import org.literacyapp.model.analytics.StudentImageCollectionEvent;

import org.literacyapp.dao.AllophoneDao;
import org.literacyapp.dao.LetterDao;
import org.literacyapp.dao.AudioDao;
import org.literacyapp.dao.ImageDao;
import org.literacyapp.dao.JoinAudiosWithLettersDao;
import org.literacyapp.dao.JoinAudiosWithNumbersDao;
import org.literacyapp.dao.JoinAudiosWithWordsDao;
import org.literacyapp.dao.JoinImagesWithLettersDao;
import org.literacyapp.dao.JoinImagesWithNumbersDao;
import org.literacyapp.dao.JoinImagesWithWordsDao;
import org.literacyapp.dao.JoinVideosWithLettersDao;
import org.literacyapp.dao.JoinVideosWithNumbersDao;
import org.literacyapp.dao.JoinVideosWithWordsDao;
import org.literacyapp.dao.VideoDao;
import org.literacyapp.dao.NumberDao;
import org.literacyapp.dao.WordDao;
import org.literacyapp.dao.DeviceDao;
import org.literacyapp.dao.JoinStudentsWithDevicesDao;
import org.literacyapp.dao.StudentDao;
import org.literacyapp.dao.StudentImageDao;
import org.literacyapp.dao.StudentImageFeatureDao;
import org.literacyapp.dao.AuthenticationEventDao;
import org.literacyapp.dao.StudentImageCollectionEventDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig allophoneDaoConfig;
    private final DaoConfig letterDaoConfig;
    private final DaoConfig audioDaoConfig;
    private final DaoConfig imageDaoConfig;
    private final DaoConfig joinAudiosWithLettersDaoConfig;
    private final DaoConfig joinAudiosWithNumbersDaoConfig;
    private final DaoConfig joinAudiosWithWordsDaoConfig;
    private final DaoConfig joinImagesWithLettersDaoConfig;
    private final DaoConfig joinImagesWithNumbersDaoConfig;
    private final DaoConfig joinImagesWithWordsDaoConfig;
    private final DaoConfig joinVideosWithLettersDaoConfig;
    private final DaoConfig joinVideosWithNumbersDaoConfig;
    private final DaoConfig joinVideosWithWordsDaoConfig;
    private final DaoConfig videoDaoConfig;
    private final DaoConfig numberDaoConfig;
    private final DaoConfig wordDaoConfig;
    private final DaoConfig deviceDaoConfig;
    private final DaoConfig joinStudentsWithDevicesDaoConfig;
    private final DaoConfig studentDaoConfig;
    private final DaoConfig studentImageDaoConfig;
    private final DaoConfig studentImageFeatureDaoConfig;
    private final DaoConfig authenticationEventDaoConfig;
    private final DaoConfig studentImageCollectionEventDaoConfig;

    private final AllophoneDao allophoneDao;
    private final LetterDao letterDao;
    private final AudioDao audioDao;
    private final ImageDao imageDao;
    private final JoinAudiosWithLettersDao joinAudiosWithLettersDao;
    private final JoinAudiosWithNumbersDao joinAudiosWithNumbersDao;
    private final JoinAudiosWithWordsDao joinAudiosWithWordsDao;
    private final JoinImagesWithLettersDao joinImagesWithLettersDao;
    private final JoinImagesWithNumbersDao joinImagesWithNumbersDao;
    private final JoinImagesWithWordsDao joinImagesWithWordsDao;
    private final JoinVideosWithLettersDao joinVideosWithLettersDao;
    private final JoinVideosWithNumbersDao joinVideosWithNumbersDao;
    private final JoinVideosWithWordsDao joinVideosWithWordsDao;
    private final VideoDao videoDao;
    private final NumberDao numberDao;
    private final WordDao wordDao;
    private final DeviceDao deviceDao;
    private final JoinStudentsWithDevicesDao joinStudentsWithDevicesDao;
    private final StudentDao studentDao;
    private final StudentImageDao studentImageDao;
    private final StudentImageFeatureDao studentImageFeatureDao;
    private final AuthenticationEventDao authenticationEventDao;
    private final StudentImageCollectionEventDao studentImageCollectionEventDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        allophoneDaoConfig = daoConfigMap.get(AllophoneDao.class).clone();
        allophoneDaoConfig.initIdentityScope(type);

        letterDaoConfig = daoConfigMap.get(LetterDao.class).clone();
        letterDaoConfig.initIdentityScope(type);

        audioDaoConfig = daoConfigMap.get(AudioDao.class).clone();
        audioDaoConfig.initIdentityScope(type);

        imageDaoConfig = daoConfigMap.get(ImageDao.class).clone();
        imageDaoConfig.initIdentityScope(type);

        joinAudiosWithLettersDaoConfig = daoConfigMap.get(JoinAudiosWithLettersDao.class).clone();
        joinAudiosWithLettersDaoConfig.initIdentityScope(type);

        joinAudiosWithNumbersDaoConfig = daoConfigMap.get(JoinAudiosWithNumbersDao.class).clone();
        joinAudiosWithNumbersDaoConfig.initIdentityScope(type);

        joinAudiosWithWordsDaoConfig = daoConfigMap.get(JoinAudiosWithWordsDao.class).clone();
        joinAudiosWithWordsDaoConfig.initIdentityScope(type);

        joinImagesWithLettersDaoConfig = daoConfigMap.get(JoinImagesWithLettersDao.class).clone();
        joinImagesWithLettersDaoConfig.initIdentityScope(type);

        joinImagesWithNumbersDaoConfig = daoConfigMap.get(JoinImagesWithNumbersDao.class).clone();
        joinImagesWithNumbersDaoConfig.initIdentityScope(type);

        joinImagesWithWordsDaoConfig = daoConfigMap.get(JoinImagesWithWordsDao.class).clone();
        joinImagesWithWordsDaoConfig.initIdentityScope(type);

        joinVideosWithLettersDaoConfig = daoConfigMap.get(JoinVideosWithLettersDao.class).clone();
        joinVideosWithLettersDaoConfig.initIdentityScope(type);

        joinVideosWithNumbersDaoConfig = daoConfigMap.get(JoinVideosWithNumbersDao.class).clone();
        joinVideosWithNumbersDaoConfig.initIdentityScope(type);

        joinVideosWithWordsDaoConfig = daoConfigMap.get(JoinVideosWithWordsDao.class).clone();
        joinVideosWithWordsDaoConfig.initIdentityScope(type);

        videoDaoConfig = daoConfigMap.get(VideoDao.class).clone();
        videoDaoConfig.initIdentityScope(type);

        numberDaoConfig = daoConfigMap.get(NumberDao.class).clone();
        numberDaoConfig.initIdentityScope(type);

        wordDaoConfig = daoConfigMap.get(WordDao.class).clone();
        wordDaoConfig.initIdentityScope(type);

        deviceDaoConfig = daoConfigMap.get(DeviceDao.class).clone();
        deviceDaoConfig.initIdentityScope(type);

        joinStudentsWithDevicesDaoConfig = daoConfigMap.get(JoinStudentsWithDevicesDao.class).clone();
        joinStudentsWithDevicesDaoConfig.initIdentityScope(type);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        studentImageDaoConfig = daoConfigMap.get(StudentImageDao.class).clone();
        studentImageDaoConfig.initIdentityScope(type);

        studentImageFeatureDaoConfig = daoConfigMap.get(StudentImageFeatureDao.class).clone();
        studentImageFeatureDaoConfig.initIdentityScope(type);

        authenticationEventDaoConfig = daoConfigMap.get(AuthenticationEventDao.class).clone();
        authenticationEventDaoConfig.initIdentityScope(type);

        studentImageCollectionEventDaoConfig = daoConfigMap.get(StudentImageCollectionEventDao.class).clone();
        studentImageCollectionEventDaoConfig.initIdentityScope(type);

        allophoneDao = new AllophoneDao(allophoneDaoConfig, this);
        letterDao = new LetterDao(letterDaoConfig, this);
        audioDao = new AudioDao(audioDaoConfig, this);
        imageDao = new ImageDao(imageDaoConfig, this);
        joinAudiosWithLettersDao = new JoinAudiosWithLettersDao(joinAudiosWithLettersDaoConfig, this);
        joinAudiosWithNumbersDao = new JoinAudiosWithNumbersDao(joinAudiosWithNumbersDaoConfig, this);
        joinAudiosWithWordsDao = new JoinAudiosWithWordsDao(joinAudiosWithWordsDaoConfig, this);
        joinImagesWithLettersDao = new JoinImagesWithLettersDao(joinImagesWithLettersDaoConfig, this);
        joinImagesWithNumbersDao = new JoinImagesWithNumbersDao(joinImagesWithNumbersDaoConfig, this);
        joinImagesWithWordsDao = new JoinImagesWithWordsDao(joinImagesWithWordsDaoConfig, this);
        joinVideosWithLettersDao = new JoinVideosWithLettersDao(joinVideosWithLettersDaoConfig, this);
        joinVideosWithNumbersDao = new JoinVideosWithNumbersDao(joinVideosWithNumbersDaoConfig, this);
        joinVideosWithWordsDao = new JoinVideosWithWordsDao(joinVideosWithWordsDaoConfig, this);
        videoDao = new VideoDao(videoDaoConfig, this);
        numberDao = new NumberDao(numberDaoConfig, this);
        wordDao = new WordDao(wordDaoConfig, this);
        deviceDao = new DeviceDao(deviceDaoConfig, this);
        joinStudentsWithDevicesDao = new JoinStudentsWithDevicesDao(joinStudentsWithDevicesDaoConfig, this);
        studentDao = new StudentDao(studentDaoConfig, this);
        studentImageDao = new StudentImageDao(studentImageDaoConfig, this);
        studentImageFeatureDao = new StudentImageFeatureDao(studentImageFeatureDaoConfig, this);
        authenticationEventDao = new AuthenticationEventDao(authenticationEventDaoConfig, this);
        studentImageCollectionEventDao = new StudentImageCollectionEventDao(studentImageCollectionEventDaoConfig, this);

        registerDao(Allophone.class, allophoneDao);
        registerDao(Letter.class, letterDao);
        registerDao(Audio.class, audioDao);
        registerDao(Image.class, imageDao);
        registerDao(JoinAudiosWithLetters.class, joinAudiosWithLettersDao);
        registerDao(JoinAudiosWithNumbers.class, joinAudiosWithNumbersDao);
        registerDao(JoinAudiosWithWords.class, joinAudiosWithWordsDao);
        registerDao(JoinImagesWithLetters.class, joinImagesWithLettersDao);
        registerDao(JoinImagesWithNumbers.class, joinImagesWithNumbersDao);
        registerDao(JoinImagesWithWords.class, joinImagesWithWordsDao);
        registerDao(JoinVideosWithLetters.class, joinVideosWithLettersDao);
        registerDao(JoinVideosWithNumbers.class, joinVideosWithNumbersDao);
        registerDao(JoinVideosWithWords.class, joinVideosWithWordsDao);
        registerDao(Video.class, videoDao);
        registerDao(Number.class, numberDao);
        registerDao(Word.class, wordDao);
        registerDao(Device.class, deviceDao);
        registerDao(JoinStudentsWithDevices.class, joinStudentsWithDevicesDao);
        registerDao(Student.class, studentDao);
        registerDao(StudentImage.class, studentImageDao);
        registerDao(StudentImageFeature.class, studentImageFeatureDao);
        registerDao(AuthenticationEvent.class, authenticationEventDao);
        registerDao(StudentImageCollectionEvent.class, studentImageCollectionEventDao);
    }
    
    public void clear() {
        allophoneDaoConfig.clearIdentityScope();
        letterDaoConfig.clearIdentityScope();
        audioDaoConfig.clearIdentityScope();
        imageDaoConfig.clearIdentityScope();
        joinAudiosWithLettersDaoConfig.clearIdentityScope();
        joinAudiosWithNumbersDaoConfig.clearIdentityScope();
        joinAudiosWithWordsDaoConfig.clearIdentityScope();
        joinImagesWithLettersDaoConfig.clearIdentityScope();
        joinImagesWithNumbersDaoConfig.clearIdentityScope();
        joinImagesWithWordsDaoConfig.clearIdentityScope();
        joinVideosWithLettersDaoConfig.clearIdentityScope();
        joinVideosWithNumbersDaoConfig.clearIdentityScope();
        joinVideosWithWordsDaoConfig.clearIdentityScope();
        videoDaoConfig.clearIdentityScope();
        numberDaoConfig.clearIdentityScope();
        wordDaoConfig.clearIdentityScope();
        deviceDaoConfig.clearIdentityScope();
        joinStudentsWithDevicesDaoConfig.clearIdentityScope();
        studentDaoConfig.clearIdentityScope();
        studentImageDaoConfig.clearIdentityScope();
        studentImageFeatureDaoConfig.clearIdentityScope();
        authenticationEventDaoConfig.clearIdentityScope();
        studentImageCollectionEventDaoConfig.clearIdentityScope();
    }

    public AllophoneDao getAllophoneDao() {
        return allophoneDao;
    }

    public LetterDao getLetterDao() {
        return letterDao;
    }

    public AudioDao getAudioDao() {
        return audioDao;
    }

    public ImageDao getImageDao() {
        return imageDao;
    }

    public JoinAudiosWithLettersDao getJoinAudiosWithLettersDao() {
        return joinAudiosWithLettersDao;
    }

    public JoinAudiosWithNumbersDao getJoinAudiosWithNumbersDao() {
        return joinAudiosWithNumbersDao;
    }

    public JoinAudiosWithWordsDao getJoinAudiosWithWordsDao() {
        return joinAudiosWithWordsDao;
    }

    public JoinImagesWithLettersDao getJoinImagesWithLettersDao() {
        return joinImagesWithLettersDao;
    }

    public JoinImagesWithNumbersDao getJoinImagesWithNumbersDao() {
        return joinImagesWithNumbersDao;
    }

    public JoinImagesWithWordsDao getJoinImagesWithWordsDao() {
        return joinImagesWithWordsDao;
    }

    public JoinVideosWithLettersDao getJoinVideosWithLettersDao() {
        return joinVideosWithLettersDao;
    }

    public JoinVideosWithNumbersDao getJoinVideosWithNumbersDao() {
        return joinVideosWithNumbersDao;
    }

    public JoinVideosWithWordsDao getJoinVideosWithWordsDao() {
        return joinVideosWithWordsDao;
    }

    public VideoDao getVideoDao() {
        return videoDao;
    }

    public NumberDao getNumberDao() {
        return numberDao;
    }

    public WordDao getWordDao() {
        return wordDao;
    }

    public DeviceDao getDeviceDao() {
        return deviceDao;
    }

    public JoinStudentsWithDevicesDao getJoinStudentsWithDevicesDao() {
        return joinStudentsWithDevicesDao;
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

    public StudentImageDao getStudentImageDao() {
        return studentImageDao;
    }

    public StudentImageFeatureDao getStudentImageFeatureDao() {
        return studentImageFeatureDao;
    }

    public AuthenticationEventDao getAuthenticationEventDao() {
        return authenticationEventDao;
    }

    public StudentImageCollectionEventDao getStudentImageCollectionEventDao() {
        return studentImageCollectionEventDao;
    }

}
