package org.literacyapp.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import org.literacyapp.dao.Allophone;
import org.literacyapp.dao.Letter;
import org.literacyapp.dao.Audio;
import org.literacyapp.dao.Word;
import org.literacyapp.dao.Number;
import org.literacyapp.dao.Image;
import org.literacyapp.dao.Video;

import org.literacyapp.dao.AllophoneDao;
import org.literacyapp.dao.LetterDao;
import org.literacyapp.dao.AudioDao;
import org.literacyapp.dao.WordDao;
import org.literacyapp.dao.NumberDao;
import org.literacyapp.dao.ImageDao;
import org.literacyapp.dao.VideoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig allophoneDaoConfig;
    private final DaoConfig letterDaoConfig;
    private final DaoConfig audioDaoConfig;
    private final DaoConfig wordDaoConfig;
    private final DaoConfig numberDaoConfig;
    private final DaoConfig imageDaoConfig;
    private final DaoConfig videoDaoConfig;

    private final AllophoneDao allophoneDao;
    private final LetterDao letterDao;
    private final AudioDao audioDao;
    private final WordDao wordDao;
    private final NumberDao numberDao;
    private final ImageDao imageDao;
    private final VideoDao videoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        allophoneDaoConfig = daoConfigMap.get(AllophoneDao.class).clone();
        allophoneDaoConfig.initIdentityScope(type);

        letterDaoConfig = daoConfigMap.get(LetterDao.class).clone();
        letterDaoConfig.initIdentityScope(type);

        audioDaoConfig = daoConfigMap.get(AudioDao.class).clone();
        audioDaoConfig.initIdentityScope(type);

        wordDaoConfig = daoConfigMap.get(WordDao.class).clone();
        wordDaoConfig.initIdentityScope(type);

        numberDaoConfig = daoConfigMap.get(NumberDao.class).clone();
        numberDaoConfig.initIdentityScope(type);

        imageDaoConfig = daoConfigMap.get(ImageDao.class).clone();
        imageDaoConfig.initIdentityScope(type);

        videoDaoConfig = daoConfigMap.get(VideoDao.class).clone();
        videoDaoConfig.initIdentityScope(type);

        allophoneDao = new AllophoneDao(allophoneDaoConfig, this);
        letterDao = new LetterDao(letterDaoConfig, this);
        audioDao = new AudioDao(audioDaoConfig, this);
        wordDao = new WordDao(wordDaoConfig, this);
        numberDao = new NumberDao(numberDaoConfig, this);
        imageDao = new ImageDao(imageDaoConfig, this);
        videoDao = new VideoDao(videoDaoConfig, this);

        registerDao(Allophone.class, allophoneDao);
        registerDao(Letter.class, letterDao);
        registerDao(Audio.class, audioDao);
        registerDao(Word.class, wordDao);
        registerDao(Number.class, numberDao);
        registerDao(Image.class, imageDao);
        registerDao(Video.class, videoDao);
    }
    
    public void clear() {
        allophoneDaoConfig.getIdentityScope().clear();
        letterDaoConfig.getIdentityScope().clear();
        audioDaoConfig.getIdentityScope().clear();
        wordDaoConfig.getIdentityScope().clear();
        numberDaoConfig.getIdentityScope().clear();
        imageDaoConfig.getIdentityScope().clear();
        videoDaoConfig.getIdentityScope().clear();
    }

    public AllophoneDao getAllophoneDao() {
        return allophoneDao;
    }

    public LetterDao getLetterDao() {
        return letterDao;
    }

    public AudioDao getAudioDao() {
        return audioDao;
    }

    public WordDao getWordDao() {
        return wordDao;
    }

    public NumberDao getNumberDao() {
        return numberDao;
    }

    public ImageDao getImageDao() {
        return imageDao;
    }

    public VideoDao getVideoDao() {
        return videoDao;
    }

}
