package org.literacyapp.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import org.literacyapp.model.content.Allophone;
import org.literacyapp.model.content.Letter;
import org.literacyapp.model.content.multimedia.Audio;
import org.literacyapp.model.content.multimedia.Image;
import org.literacyapp.model.content.multimedia.JoinVideosWithLetters;
import org.literacyapp.model.content.multimedia.Video;
import org.literacyapp.model.content.Number;
import org.literacyapp.model.content.Word;
import org.literacyapp.model.Device;
import org.literacyapp.model.Student;
import org.literacyapp.model.StudentImage;
import org.literacyapp.model.StudentImageCollectionEvent;
import org.literacyapp.model.StudentImageFeature;

import org.literacyapp.dao.AllophoneDao;
import org.literacyapp.dao.LetterDao;
import org.literacyapp.dao.AudioDao;
import org.literacyapp.dao.ImageDao;
import org.literacyapp.dao.JoinVideosWithLettersDao;
import org.literacyapp.dao.VideoDao;
import org.literacyapp.dao.NumberDao;
import org.literacyapp.dao.WordDao;
import org.literacyapp.dao.DeviceDao;
import org.literacyapp.dao.StudentDao;
import org.literacyapp.dao.StudentImageDao;
import org.literacyapp.dao.StudentImageCollectionEventDao;
import org.literacyapp.dao.StudentImageFeatureDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig allophoneDaoConfig;
    private final DaoConfig letterDaoConfig;
    private final DaoConfig audioDaoConfig;
    private final DaoConfig imageDaoConfig;
    private final DaoConfig joinVideosWithLettersDaoConfig;
    private final DaoConfig videoDaoConfig;
    private final DaoConfig numberDaoConfig;
    private final DaoConfig wordDaoConfig;
    private final DaoConfig deviceDaoConfig;
    private final DaoConfig studentDaoConfig;
    private final DaoConfig studentImageDaoConfig;
    private final DaoConfig studentImageCollectionEventDaoConfig;
    private final DaoConfig studentImageFeatureDaoConfig;

    private final AllophoneDao allophoneDao;
    private final LetterDao letterDao;
    private final AudioDao audioDao;
    private final ImageDao imageDao;
    private final JoinVideosWithLettersDao joinVideosWithLettersDao;
    private final VideoDao videoDao;
    private final NumberDao numberDao;
    private final WordDao wordDao;
    private final DeviceDao deviceDao;
    private final StudentDao studentDao;
    private final StudentImageDao studentImageDao;
    private final StudentImageCollectionEventDao studentImageCollectionEventDao;
    private final StudentImageFeatureDao studentImageFeatureDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        allophoneDaoConfig = daoConfigMap.get(AllophoneDao.class).clone();
        allophoneDaoConfig.initIdentityScope(type);

        letterDaoConfig = daoConfigMap.get(LetterDao.class).clone();
        letterDaoConfig.initIdentityScope(type);

        audioDaoConfig = daoConfigMap.get(AudioDao.class).clone();
        audioDaoConfig.initIdentityScope(type);

        imageDaoConfig = daoConfigMap.get(ImageDao.class).clone();
        imageDaoConfig.initIdentityScope(type);

        joinVideosWithLettersDaoConfig = daoConfigMap.get(JoinVideosWithLettersDao.class).clone();
        joinVideosWithLettersDaoConfig.initIdentityScope(type);

        videoDaoConfig = daoConfigMap.get(VideoDao.class).clone();
        videoDaoConfig.initIdentityScope(type);

        numberDaoConfig = daoConfigMap.get(NumberDao.class).clone();
        numberDaoConfig.initIdentityScope(type);

        wordDaoConfig = daoConfigMap.get(WordDao.class).clone();
        wordDaoConfig.initIdentityScope(type);

        deviceDaoConfig = daoConfigMap.get(DeviceDao.class).clone();
        deviceDaoConfig.initIdentityScope(type);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        studentImageDaoConfig = daoConfigMap.get(StudentImageDao.class).clone();
        studentImageDaoConfig.initIdentityScope(type);

        studentImageCollectionEventDaoConfig = daoConfigMap.get(StudentImageCollectionEventDao.class).clone();
        studentImageCollectionEventDaoConfig.initIdentityScope(type);

        studentImageFeatureDaoConfig = daoConfigMap.get(StudentImageFeatureDao.class).clone();
        studentImageFeatureDaoConfig.initIdentityScope(type);

        allophoneDao = new AllophoneDao(allophoneDaoConfig, this);
        letterDao = new LetterDao(letterDaoConfig, this);
        audioDao = new AudioDao(audioDaoConfig, this);
        imageDao = new ImageDao(imageDaoConfig, this);
        joinVideosWithLettersDao = new JoinVideosWithLettersDao(joinVideosWithLettersDaoConfig, this);
        videoDao = new VideoDao(videoDaoConfig, this);
        numberDao = new NumberDao(numberDaoConfig, this);
        wordDao = new WordDao(wordDaoConfig, this);
        deviceDao = new DeviceDao(deviceDaoConfig, this);
        studentDao = new StudentDao(studentDaoConfig, this);
        studentImageDao = new StudentImageDao(studentImageDaoConfig, this);
        studentImageCollectionEventDao = new StudentImageCollectionEventDao(studentImageCollectionEventDaoConfig, this);
        studentImageFeatureDao = new StudentImageFeatureDao(studentImageFeatureDaoConfig, this);

        registerDao(Allophone.class, allophoneDao);
        registerDao(Letter.class, letterDao);
        registerDao(Audio.class, audioDao);
        registerDao(Image.class, imageDao);
        registerDao(JoinVideosWithLetters.class, joinVideosWithLettersDao);
        registerDao(Video.class, videoDao);
        registerDao(Number.class, numberDao);
        registerDao(Word.class, wordDao);
        registerDao(Device.class, deviceDao);
        registerDao(Student.class, studentDao);
        registerDao(StudentImage.class, studentImageDao);
        registerDao(StudentImageCollectionEvent.class, studentImageCollectionEventDao);
        registerDao(StudentImageFeature.class, studentImageFeatureDao);
    }
    
    public void clear() {
        allophoneDaoConfig.clearIdentityScope();
        letterDaoConfig.clearIdentityScope();
        audioDaoConfig.clearIdentityScope();
        imageDaoConfig.clearIdentityScope();
        joinVideosWithLettersDaoConfig.clearIdentityScope();
        videoDaoConfig.clearIdentityScope();
        numberDaoConfig.clearIdentityScope();
        wordDaoConfig.clearIdentityScope();
        deviceDaoConfig.clearIdentityScope();
        studentDaoConfig.clearIdentityScope();
        studentImageDaoConfig.clearIdentityScope();
        studentImageCollectionEventDaoConfig.clearIdentityScope();
        studentImageFeatureDaoConfig.clearIdentityScope();
    }

    public AllophoneDao getAllophoneDao() {
        return allophoneDao;
    }

    public LetterDao getLetterDao() {
        return letterDao;
    }

    public AudioDao getAudioDao() {
        return audioDao;
    }

    public ImageDao getImageDao() {
        return imageDao;
    }

    public JoinVideosWithLettersDao getJoinVideosWithLettersDao() {
        return joinVideosWithLettersDao;
    }

    public VideoDao getVideoDao() {
        return videoDao;
    }

    public NumberDao getNumberDao() {
        return numberDao;
    }

    public WordDao getWordDao() {
        return wordDao;
    }

    public DeviceDao getDeviceDao() {
        return deviceDao;
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

    public StudentImageDao getStudentImageDao() {
        return studentImageDao;
    }

    public StudentImageCollectionEventDao getStudentImageCollectionEventDao() {
        return studentImageCollectionEventDao;
    }

    public StudentImageFeatureDao getStudentImageFeatureDao() {
        return studentImageFeatureDao;
    }

}
