package org.literacyapp.dao;

import org.literacyapp.model.enums.content.ContentStatus;
import org.literacyapp.model.enums.content.ImageFormat;

import java.util.Calendar;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "IMAGE".
 */
public class Face {

    private Long id;
    private Calendar timeLastUpdate;
    private Calendar timeCreated;
    private Boolean featureExtracted;
    private String fileUrl;
    private Integer fileSize;
    private String contentType;
    private ImageFormat imageFormat;
    private Long deviceId;
    private Long eventId;

    public Face() {
    }

    public Face(Long id) {
        this.id = id;
    }

    public Face(Long id, Calendar timeLastUpdate, Calendar timeCreated, Boolean featureExtracted, String fileUrl, Integer fileSize, String contentType, ImageFormat imageFormat, Long deviceId, Long eventId) {
        this.id = id;
        this.timeLastUpdate = timeLastUpdate;
        this.timeCreated = timeCreated;
        this.featureExtracted = featureExtracted;
        this.fileUrl = fileUrl;
        this.fileSize = fileSize;
        this.contentType = contentType;
        this.imageFormat = imageFormat;
        this.deviceId = deviceId;
        this.eventId = eventId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Calendar getTimeLastUpdate() {
        return timeLastUpdate;
    }

    public void setTimeLastUpdate(Calendar timeLastUpdate) {
        this.timeLastUpdate = timeLastUpdate;
    }

    public Calendar getTimeCreated() {
        return timeCreated;
    }

    public void setTimeCreated(Calendar timeLastUpdate) {
        this.timeCreated = timeCreated;
    }

    public Boolean getFeatureExtracted() {
        return featureExtracted;
    }

    public void setFeatureExtracted(Boolean featureExtracted) {
        this.featureExtracted = featureExtracted;
    }

    public String getFileUrl() {
        return fileUrl;
    }

    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl;
    }

    public Integer getFileSize() {
        return fileSize;
    }

    public void setFileSize(Integer fileSize) {
        this.fileSize = fileSize;
    }

    public String getContentType() {
        return contentType;
    }

    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    public ImageFormat getImageFormat() {
        return imageFormat;
    }

    public void setImageFormat(ImageFormat imageFormat) {
        this.imageFormat = imageFormat;
    }

    public Long getDeviceId() {
        return deviceId;
    }

    public void setDeviceId(Long deviceId) {
        this.deviceId = deviceId;
    }

    public Long getEventId() {
        return eventId;
    }

    public void setEventId(Long eventId) {
        this.eventId = eventId;
    }

}
