package org.literacyapp.dao;

import org.literacyapp.model.enums.content.ImageFormat;

import java.util.Calendar;
import java.util.List;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "IMAGE".
 */
public class Feature {

    private Long id;
    private Calendar timeCreated;
    private List<Float> vectors;
    private Long faceId;
    private Long studentId;

    public Feature() {
    }

    public Feature(Long id) {
        this.id = id;
    }

    public Feature(Long id, Calendar timeLastUpdate, Calendar timeCreated, Boolean featureExtracted, String fileUrl, Integer fileSize, List<Float> vectors, ImageFormat imageFormat, Long faceId, Long studentId) {
        this.id = id;
        this.timeCreated = timeCreated;
        this.vectors = vectors;
        this.faceId = faceId;
        this.studentId = studentId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Calendar getTimeCreated() {
        return timeCreated;
    }

    public void setTimeCreated(Calendar timeLastUpdate) {
        this.timeCreated = timeCreated;
    }

    public List<Float> getVectors() {
        return vectors;
    }

    public void setVectors(List<Float> vectors) {
        this.vectors = vectors;
    }

    public Long getFaceId() {
        return faceId;
    }

    public void setFaceId(Long faceId) {
        this.faceId = faceId;
    }

    public Long getStudentId() {
        return studentId;
    }

    public void setStudentId(Long studentId) {
        this.studentId = studentId;
    }

}
