package org.literacyapp.dao;

import org.literacyapp.model.enums.content.ImageType;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "IMAGE".
 */
public class Image {

    private Long id;
    private String title;
    private ImageType imageType;
    private String dominantColor;

    public Image() {
    }

    public Image(Long id) {
        this.id = id;
    }

    public Image(Long id, String title, ImageType imageType, String dominantColor) {
        this.id = id;
        this.title = title;
        this.imageType = imageType;
        this.dominantColor = dominantColor;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public ImageType getImageType() {
        return imageType;
    }

    public void setImageType(ImageType imageType) {
        this.imageType = imageType;
    }

    public String getDominantColor() {
        return dominantColor;
    }

    public void setDominantColor(String dominantColor) {
        this.dominantColor = dominantColor;
    }

}
