package org.literacyapp.dao;

import java.util.Calendar;
import java.util.Set;
import org.literacyapp.model.enums.Locale;
import org.literacyapp.model.enums.content.ContentStatus;
import org.literacyapp.model.enums.content.ImageFormat;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "IMAGE".
 */
public class Image {

    private Long id;
    private Locale locale;
    private Calendar timeLastUpdate;
    private Integer revisionNumber;
    private ContentStatus contentStatus;
    private String fileUrl;
    private Integer fileSize;
    private String contentType;
    private String attributionUrl;
    private Set literacySkills;
    private Set numeracySkills;
    private String title;
    private ImageFormat imageFormat;
    private String dominantColor;

    public Image() {
    }

    public Image(Long id) {
        this.id = id;
    }

    public Image(Long id, Locale locale, Calendar timeLastUpdate, Integer revisionNumber, ContentStatus contentStatus, String fileUrl, Integer fileSize, String contentType, String attributionUrl, Set literacySkills, Set numeracySkills, String title, ImageFormat imageFormat, String dominantColor) {
        this.id = id;
        this.locale = locale;
        this.timeLastUpdate = timeLastUpdate;
        this.revisionNumber = revisionNumber;
        this.contentStatus = contentStatus;
        this.fileUrl = fileUrl;
        this.fileSize = fileSize;
        this.contentType = contentType;
        this.attributionUrl = attributionUrl;
        this.literacySkills = literacySkills;
        this.numeracySkills = numeracySkills;
        this.title = title;
        this.imageFormat = imageFormat;
        this.dominantColor = dominantColor;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Locale getLocale() {
        return locale;
    }

    public void setLocale(Locale locale) {
        this.locale = locale;
    }

    public Calendar getTimeLastUpdate() {
        return timeLastUpdate;
    }

    public void setTimeLastUpdate(Calendar timeLastUpdate) {
        this.timeLastUpdate = timeLastUpdate;
    }

    public Integer getRevisionNumber() {
        return revisionNumber;
    }

    public void setRevisionNumber(Integer revisionNumber) {
        this.revisionNumber = revisionNumber;
    }

    public ContentStatus getContentStatus() {
        return contentStatus;
    }

    public void setContentStatus(ContentStatus contentStatus) {
        this.contentStatus = contentStatus;
    }

    public String getFileUrl() {
        return fileUrl;
    }

    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl;
    }

    public Integer getFileSize() {
        return fileSize;
    }

    public void setFileSize(Integer fileSize) {
        this.fileSize = fileSize;
    }

    public String getContentType() {
        return contentType;
    }

    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    public String getAttributionUrl() {
        return attributionUrl;
    }

    public void setAttributionUrl(String attributionUrl) {
        this.attributionUrl = attributionUrl;
    }

    public Set getLiteracySkills() {
        return literacySkills;
    }

    public void setLiteracySkills(Set literacySkills) {
        this.literacySkills = literacySkills;
    }

    public Set getNumeracySkills() {
        return numeracySkills;
    }

    public void setNumeracySkills(Set numeracySkills) {
        this.numeracySkills = numeracySkills;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public ImageFormat getImageFormat() {
        return imageFormat;
    }

    public void setImageFormat(ImageFormat imageFormat) {
        this.imageFormat = imageFormat;
    }

    public String getDominantColor() {
        return dominantColor;
    }

    public void setDominantColor(String dominantColor) {
        this.dominantColor = dominantColor;
    }

}
