package org.literacyapp.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import org.literacyapp.model.content.multimedia.JoinImagesWithWords;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "JOIN_IMAGES_WITH_WORDS".
*/
public class JoinImagesWithWordsDao extends AbstractDao<JoinImagesWithWords, Long> {

    public static final String TABLENAME = "JOIN_IMAGES_WITH_WORDS";

    /**
     * Properties of entity JoinImagesWithWords.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ImageId = new Property(1, long.class, "imageId", false, "IMAGE_ID");
        public final static Property WordId = new Property(2, long.class, "wordId", false, "WORD_ID");
    }


    public JoinImagesWithWordsDao(DaoConfig config) {
        super(config);
    }
    
    public JoinImagesWithWordsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"JOIN_IMAGES_WITH_WORDS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"IMAGE_ID\" INTEGER NOT NULL ," + // 1: imageId
                "\"WORD_ID\" INTEGER NOT NULL );"); // 2: wordId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"JOIN_IMAGES_WITH_WORDS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, JoinImagesWithWords entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getImageId());
        stmt.bindLong(3, entity.getWordId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, JoinImagesWithWords entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getImageId());
        stmt.bindLong(3, entity.getWordId());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public JoinImagesWithWords readEntity(Cursor cursor, int offset) {
        JoinImagesWithWords entity = new JoinImagesWithWords( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // imageId
            cursor.getLong(offset + 2) // wordId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, JoinImagesWithWords entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setImageId(cursor.getLong(offset + 1));
        entity.setWordId(cursor.getLong(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(JoinImagesWithWords entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(JoinImagesWithWords entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(JoinImagesWithWords entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
