package org.literacyapp.dao;

import org.literacyapp.model.enums.Locale;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LETTER".
 */
public class Letter {

    private Long id;
    private Locale locale;
    private String text;

    public Letter() {
    }

    public Letter(Long id) {
        this.id = id;
    }

    public Letter(Long id, Locale locale, String text) {
        this.id = id;
        this.locale = locale;
        this.text = text;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Locale getLocale() {
        return locale;
    }

    public void setLocale(Locale locale) {
        this.locale = locale;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

}
