package org.literacyapp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LETTER".
 */
public class Letter {

    private Long id;
    private Long serverId;
    private String language;
    private String text;

    public Letter() {
    }

    public Letter(Long id) {
        this.id = id;
    }

    public Letter(Long id, Long serverId, String language, String text) {
        this.id = id;
        this.serverId = serverId;
        this.language = language;
        this.text = text;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getServerId() {
        return serverId;
    }

    public void setServerId(Long serverId) {
        this.serverId = serverId;
    }

    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

}
