package org.literacyapp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "NUMBER".
 */
public class Number {

    private Long id;
    private String language;
    private Integer value;

    public Number() {
    }

    public Number(Long id) {
        this.id = id;
    }

    public Number(Long id, String language, Integer value) {
        this.id = id;
        this.language = language;
        this.value = value;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public Integer getValue() {
        return value;
    }

    public void setValue(Integer value) {
        this.value = value;
    }

}
