package org.literacyapp.dao;

import java.util.Set;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "STUDENT".
 */
public class Student {

    private Long id;
    private String avatarFileUrl;
    private Set devices;

    public Student() {
    }

    public Student(Long id) {
        this.id = id;
    }

    public Student(Long id, String avatarFileUrl, Set devices) {
        this.id = id;
        this.avatarFileUrl = avatarFileUrl;
        this.devices = devices;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAvatarFileUrl() {
        return avatarFileUrl;
    }

    public void setAvatarFileUrl(String avatarFileUrl) {
        this.avatarFileUrl = avatarFileUrl;
    }

    public Set getDevices() {
        return devices;
    }

    public void setDevices(Set devices) {
        this.devices = devices;
    }

}
