package org.literacyapp.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import java.util.Calendar;
import org.literacyapp.dao.converter.CalendarConverter;

import org.literacyapp.dao.StudentImage;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "STUDENT_IMAGE".
*/
public class StudentImageDao extends AbstractDao<StudentImage, Long> {

    public static final String TABLENAME = "STUDENT_IMAGE";

    /**
     * Properties of entity StudentImage.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property DeviceId = new Property(1, Long.class, "deviceId", false, "DEVICE_ID");
        public final static Property ImageFileUrl = new Property(2, String.class, "imageFileUrl", false, "IMAGE_FILE_URL");
        public final static Property TimeCollected = new Property(3, Long.class, "timeCollected", false, "TIME_COLLECTED");
        public final static Property StudentImageFeatureId = new Property(4, Long.class, "studentImageFeatureId", false, "STUDENT_IMAGE_FEATURE_ID");
    };

    private DaoSession daoSession;

    private final CalendarConverter timeCollectedConverter = new CalendarConverter();

    public StudentImageDao(DaoConfig config) {
        super(config);
    }
    
    public StudentImageDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"STUDENT_IMAGE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"DEVICE_ID\" INTEGER," + // 1: deviceId
                "\"IMAGE_FILE_URL\" TEXT," + // 2: imageFileUrl
                "\"TIME_COLLECTED\" INTEGER," + // 3: timeCollected
                "\"STUDENT_IMAGE_FEATURE_ID\" INTEGER);"); // 4: studentImageFeatureId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"STUDENT_IMAGE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, StudentImage entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long deviceId = entity.getDeviceId();
        if (deviceId != null) {
            stmt.bindLong(2, deviceId);
        }
 
        String imageFileUrl = entity.getImageFileUrl();
        if (imageFileUrl != null) {
            stmt.bindString(3, imageFileUrl);
        }
 
        Calendar timeCollected = entity.getTimeCollected();
        if (timeCollected != null) {
            stmt.bindLong(4, timeCollectedConverter.convertToDatabaseValue(timeCollected));
        }
 
        Long studentImageFeatureId = entity.getStudentImageFeatureId();
        if (studentImageFeatureId != null) {
            stmt.bindLong(5, studentImageFeatureId);
        }
    }

    @Override
    protected void attachEntity(StudentImage entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public StudentImage readEntity(Cursor cursor, int offset) {
        StudentImage entity = new StudentImage( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // deviceId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // imageFileUrl
            cursor.isNull(offset + 3) ? null : timeCollectedConverter.convertToEntityProperty(cursor.getLong(offset + 3)), // timeCollected
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // studentImageFeatureId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, StudentImage entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDeviceId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setImageFileUrl(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTimeCollected(cursor.isNull(offset + 3) ? null : timeCollectedConverter.convertToEntityProperty(cursor.getLong(offset + 3)));
        entity.setStudentImageFeatureId(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(StudentImage entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(StudentImage entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getDeviceDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getStudentImageFeatureDao().getAllColumns());
            builder.append(" FROM STUDENT_IMAGE T");
            builder.append(" LEFT JOIN DEVICE T0 ON T.\"DEVICE_ID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN STUDENT_IMAGE_FEATURE T1 ON T.\"STUDENT_IMAGE_FEATURE_ID\"=T1.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected StudentImage loadCurrentDeep(Cursor cursor, boolean lock) {
        StudentImage entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Device device = loadCurrentOther(daoSession.getDeviceDao(), cursor, offset);
        entity.setDevice(device);
        offset += daoSession.getDeviceDao().getAllColumns().length;

        StudentImageFeature studentImageFeature = loadCurrentOther(daoSession.getStudentImageFeatureDao(), cursor, offset);
        entity.setStudentImageFeature(studentImageFeature);

        return entity;    
    }

    public StudentImage loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<StudentImage> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<StudentImage> list = new ArrayList<StudentImage>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<StudentImage> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<StudentImage> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
