package org.literacyapp.dao;

import java.util.Calendar;
import java.util.Set;
import org.literacyapp.model.enums.Locale;
import org.literacyapp.model.enums.content.VideoFormat;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "VIDEO".
 */
public class Video {

    private Long id;
    private Locale locale;
    private Calendar timeLastUpdate;
    private Integer revisionNumber;
    private String fileUrl;
    private Integer fileSize;
    private String contentType;
    private String attributionUrl;
    private Set literacySkills;
    private Set numeracySkills;
    private String title;
    private VideoFormat videoFormat;

    public Video() {
    }

    public Video(Long id) {
        this.id = id;
    }

    public Video(Long id, Locale locale, Calendar timeLastUpdate, Integer revisionNumber, String fileUrl, Integer fileSize, String contentType, String attributionUrl, Set literacySkills, Set numeracySkills, String title, VideoFormat videoFormat) {
        this.id = id;
        this.locale = locale;
        this.timeLastUpdate = timeLastUpdate;
        this.revisionNumber = revisionNumber;
        this.fileUrl = fileUrl;
        this.fileSize = fileSize;
        this.contentType = contentType;
        this.attributionUrl = attributionUrl;
        this.literacySkills = literacySkills;
        this.numeracySkills = numeracySkills;
        this.title = title;
        this.videoFormat = videoFormat;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Locale getLocale() {
        return locale;
    }

    public void setLocale(Locale locale) {
        this.locale = locale;
    }

    public Calendar getTimeLastUpdate() {
        return timeLastUpdate;
    }

    public void setTimeLastUpdate(Calendar timeLastUpdate) {
        this.timeLastUpdate = timeLastUpdate;
    }

    public Integer getRevisionNumber() {
        return revisionNumber;
    }

    public void setRevisionNumber(Integer revisionNumber) {
        this.revisionNumber = revisionNumber;
    }

    public String getFileUrl() {
        return fileUrl;
    }

    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl;
    }

    public Integer getFileSize() {
        return fileSize;
    }

    public void setFileSize(Integer fileSize) {
        this.fileSize = fileSize;
    }

    public String getContentType() {
        return contentType;
    }

    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    public String getAttributionUrl() {
        return attributionUrl;
    }

    public void setAttributionUrl(String attributionUrl) {
        this.attributionUrl = attributionUrl;
    }

    public Set getLiteracySkills() {
        return literacySkills;
    }

    public void setLiteracySkills(Set literacySkills) {
        this.literacySkills = literacySkills;
    }

    public Set getNumeracySkills() {
        return numeracySkills;
    }

    public void setNumeracySkills(Set numeracySkills) {
        this.numeracySkills = numeracySkills;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public VideoFormat getVideoFormat() {
        return videoFormat;
    }

    public void setVideoFormat(VideoFormat videoFormat) {
        this.videoFormat = videoFormat;
    }

}
