package org.literacyapp.contentprovider.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import org.literacyapp.contentprovider.model.JoinLettersWithAllophones;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "JOIN_LETTERS_WITH_ALLOPHONES".
*/
public class JoinLettersWithAllophonesDao extends AbstractDao<JoinLettersWithAllophones, Long> {

    public static final String TABLENAME = "JOIN_LETTERS_WITH_ALLOPHONES";

    /**
     * Properties of entity JoinLettersWithAllophones.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property LetterId = new Property(1, long.class, "letterId", false, "LETTER_ID");
        public final static Property AllophoneId = new Property(2, long.class, "allophoneId", false, "ALLOPHONE_ID");
    }


    public JoinLettersWithAllophonesDao(DaoConfig config) {
        super(config);
    }
    
    public JoinLettersWithAllophonesDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"JOIN_LETTERS_WITH_ALLOPHONES\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"LETTER_ID\" INTEGER NOT NULL ," + // 1: letterId
                "\"ALLOPHONE_ID\" INTEGER NOT NULL );"); // 2: allophoneId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"JOIN_LETTERS_WITH_ALLOPHONES\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, JoinLettersWithAllophones entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getLetterId());
        stmt.bindLong(3, entity.getAllophoneId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, JoinLettersWithAllophones entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getLetterId());
        stmt.bindLong(3, entity.getAllophoneId());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public JoinLettersWithAllophones readEntity(Cursor cursor, int offset) {
        JoinLettersWithAllophones entity = new JoinLettersWithAllophones( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // letterId
            cursor.getLong(offset + 2) // allophoneId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, JoinLettersWithAllophones entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setLetterId(cursor.getLong(offset + 1));
        entity.setAllophoneId(cursor.getLong(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(JoinLettersWithAllophones entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(JoinLettersWithAllophones entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(JoinLettersWithAllophones entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
